CREATE TABLE Cartelera (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(150) NOT NULL,
    director VARCHAR2(50) NOT NULL,
    anio NUMBER NOT NULL,
    duracion NUMBER,
    genero VARCHAR2(30) NOT NULL
);

INSERT INTO Cartelera (titulo, director, anio, duracion, genero) VALUES
('Inception','Christopher Nolan',2010,148,'Ciencia Ficcion'),
('Titanic','James Cameron',1997,195,'Drama');
INSERT INTO Cartelera (titulo, director, anio, duracion, genero) VALUES
('The Dark Knight','Christopher Nolan',2008,152,'Accion'),
('Forrest Gump','Robert Zemeckis',1994,142,'Drama'),
('The Matrix','The Wachowskis',1999,136,'Ciencia Ficcion'),
('Gladiator','Ridley Scott',2000,155,'Accion'),
('Avatar','James Cameron',2009,162,'Ciencia Ficcion'),
('The Shawshank Redemption','Frank Darabont',1994,142,'Drama'),
('Pulp Fiction','Quentin Tarantino',1994,154,'Crime'),
('The Godfather','Francis Ford Coppola',1972,175,'Crime');